### ISSUE TITLE
Feature request: filter and modify status

### ISSUE THREAD

**Issue by kstenschke** [ol-loginov/idea-task-browser#10]
With a filter to list issues by status, and an option to modify issue status, the task-browser would be a great tool to work with issue lists directly from the IDE, without the need to open the browser additionally.

**Comment by ol-loginov** [comment]
Version 0.1.13 has a simple filter.
Please note, that not every task repository provide task state, so generic "show task without state" option has been added to the filter list

![filter](https://cloud.githubusercontent.com/assets/1007300/5956049/61615e32-a7ba-11e4-9d65-8e39a8ecc042.jpg)

**Comment by ol-loginov** [comment]
Leave as is for now
