### ISSUE TITLE
Update Mantis ticket at VCS commit ?

### ISSUE THREAD

**Issue by java-artisan** [ol-loginov/idea-task-browser#11]
Would it be possible to implicitly update a Mantis ticket when a commit is made to the source control ? This way the owner of the ticket sees the activity happening for his/her ticket.

Thanks ! :-)

**Comment by ol-loginov** [comment]
It should be somewhere in "commit changes" UI.
I don't think it's reasonable to include such function (if it's possible anyway), because it doesn't have commit functionality at all. This plugin cannot change your tasks in any way

**Comment by ol-loginov** [comment]
Leave as is
