### ISSUE TITLE
Buttons not displayed

### ISSUE THREAD

**Issue by jorrit** [ol-loginov/idea-task-browser#19]
The buttons to start a task etc. are no longer displayed:

![image](https://user-images.githubusercontent.com/521449/89790852-d8bf2d00-db22-11ea-8e30-78c7fe30ab1f.png)

I found the following warnings/errors related to TaskBrowser in my log file:

> 2020-08-06 14:18:34,457 [271655706]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  TaskBrowser) or icon jar:file:/C:/Users/Jorrit/AppData/Local/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.6397.71/lib/icons.jar!/general/moreTabs.png 

> 2020-08-10 07:13:00,824 [591722073]   WARN - .AbstractProgressIndicatorBase - This progress indicator is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress.
org.github.olloginov.ideataskbrowser.tasks.FetchNewIssuesFromRepoTask.updateCurrent(FetchNewIssuesFromRepoTask.java:192) 

My installation:

PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020
Licensed to nCode / Jorrit Schippers
Subscription is active until April 30, 2021
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1502M
Cores: 4
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, js.debugger.webconsole=false
Non-Bundled Plugins: com.dubreuia, String Manipulation, wide-task-browser, name.kropp.intellij.makefile, mobi.hsz.idea.gitignore, com.intellij.lang.jsgraphql, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv

**Comment by ol-loginov** [comment]
First of all, let's check some settings:

1) click on gear icon at top-right corner of toolwindow
2) and check "Show Toolbar" option in popup menu.

I hope this helps

![screenshot_2020-08-14_20-05-33](https://user-images.githubusercontent.com/1007300/90274905-147f2d00-de6a-11ea-899f-4a96491f4228.png)

**Comment by jorrit** [comment]
Thanks for your answer. I will check the status of that toggle the next time the task bar buttons disappear.
