### ISSUE TITLE
Feature request: show issue description on right panel

### ISSUE THREAD

**Issue by axelcostaspena** [ol-loginov/idea-task-browser#4]
By the way, what is right panel for? It's emtpy!
![20130613_104056_001](https://f.cloud.github.com/assets/2345716/647452/411ddd1a-d405-11e2-9d89-d2d5e3d63e36.png)

**Comment by axelcostaspena** [comment]
@ol-loginov heartens from Spain!

**Comment by axelcostaspena** [comment]
Already done, am I right?

**Comment by ol-loginov** [comment]
Yes, indeed

**Comment by Tagakov** [comment]
I think this issue should be closed
