### ISSUE TITLE
Error - Cannot fetch remote changes

### ISSUE THREAD

**Issue by JenSmith** [ol-loginov/idea-task-browser#6]
I'm currently using Redmine 2.3.1 and PyCharm; PyCharm itself is able to load tasks from the Redmine server without problems.  However, this plugin throws an error every time I try to load data from it.  

Not sure if it's a bug or just user error, really hoping to get this one working as viewing a list of issues is something I rather miss from Eclipse.

**Comment by kstenschke** [comment]
I am having the same issue, using Mantisbt 1.2.17:
When clicking the "get latest updates from server" button, the "Cannot fetch remote changes"  error notification is displayed. The server is correctly configured, logging-in and listing tasks works with the default Jetbrains "Task Management" plugin.

**Comment by ol-loginov** [comment]
Please wait for version 0.1.11 and let me know if it works

**Comment by kstenschke** [comment]
Fetching issues from MantisBT works now :) thanks a lot!

**Comment by ol-loginov** [comment]
No prob
