### ISSUE TITLE
Respect IDE options for tasks

### ISSUE THREAD

**Issue by mfutselaar** [ol-loginov/idea-task-browser#8]
If you decide to use YouTrack as the issue tracker, you get the option to set the state of the task to in progress/resolved.

This works fine using the built-in task browser, your plugin however doesn't do anything with these options and leaves my tasks open instead of setting it to "in progress" when I open the task.

![youtrack](https://cloud.githubusercontent.com/assets/6617049/5067535/ec953c7c-6e43-11e4-9145-74ac290748a9.png)

**Comment by ol-loginov** [comment]
It's specific to YouTrac.

Could you please explain how do these options works?

**Comment by mfutselaar** [comment]
Indeed, see this screenshot here:

![github](https://cloud.githubusercontent.com/assets/6617049/5857055/0a4c67b6-a249-11e4-9150-5d8f398d9c98.png)

Technically, all the task browser has to do is the "mark as in progress" bit, seeing the plugin doesn't support closing tasks yet, I wouldn't bother with the close issue bit.

**Comment by ol-loginov** [comment]
Please, try version 0.1.12
Standard 'open task' dialog is used in that build
