### ISSUE TITLE
Plugin aborts IDE startup with exception "cannot load project"

### ISSUE THREAD

**Issue by kstenschke** [ol-loginov/idea-task-browser#9]
After installing the plugin in IntellJ IDEA 14 (build #IU-139.659) i cannot load any project, the following error message is thrown: 

Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException:com.intellij.diagnostic.PluginException: or/github/olloginov/ideataskbrowser/TaskBrowserNotifier : Unsupported major.minor version 51.0 (Plugin: wide-task-browser)

**Comment by ol-loginov** [comment]
Thaks for feedback!

Please, try next version - 0.1.10
